### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by Aloso** [Aloso/lexical-sort#3]
This crate currently doesn't support `no_std`, because its dependency [`any_ascii`](https://lib.rs/crates/any_ascii) doesn't. However, it should be simple to add `no_std` support to `any_ascii` as well as `lexical-sort`.

**Comment by casept** [comment]
I need this feature in a GBA game I'm writing. I've already submitted a PR against `anyascii` (https://github.com/anyascii/anyascii/pull/1).

Just noticed that I may need to talk to the crate's maintainer though, as the Rust version used in CI is so ancient that it predates `alloc` stabilization.

**Comment by Aloso** [comment]
Thanks for doing this! I'll add `no_std` support once the PR lands on anyascii.

**Comment by Aloso** [comment]
@casept since `no_std` support in `anyascii` was merged recently, I added `no_std` support as well. I'll publish a new release now, check it out!

**Comment by casept** [comment]
Thank you!
